Credential handling
cloudquery/cq-provider-digitalocean pull request #28
Opened 2022-01-03 19:03 UTC by bbernays

Spaces Credentials are only used when grabbing Spaces resource. So needed a way of notifying the user of only when interacting with Spaces.

Did not want to parse Errors from S3/Spaces because of the complexity. 

Open to returning an error prior to the call if Credentials are not set

2022-01-06 07:56 UTC, roneli requested changes
Agree with the change, I think we can improve a little over the current proposal

2022-01-06 07:56 UTC, roneli commented on resources/spaces.go
> +		if !svc.CredentialStatus.Spaces {
why not check this before doing the call, if its not set the call won't work. Seems you don't check the other API field, so maybe just check if s3 client is nil, imo this should return a diagnostic that you called Spaces API but didn't set client key.

2022-01-06 13:24 UTC, bbernays commented on resources/spaces.go
> +		if !svc.CredentialStatus.Spaces {
I put it here incase the bucket was fully public

2022-01-09 21:09 UTC, yevgenypats requested changes
looks good one comment

2022-01-09 21:09 UTC, yevgenypats commented on resources/spaces.go
> +		if !svc.CredentialStatus.Spaces {
In that case I would do the following:

```
if !svc.CredentialStatus.Spaces {
    log.Warn("Spaces credentials not set. skipping")
    return nil
} else {
   return err
}
```

2022-01-17 18:42 UTC, zagronitay commented on client/client.go
> +	Api    bool
Not sure if needed
I don't see any usage

2022-01-17 18:44 UTC, bbernays commented on client/client.go
> +	Api    bool
I don't think it is, but I had put it in there for completeness.

2022-01-17 18:50 UTC, zagronitay approved these changes
LGTM

2022-01-17 20:06 UTC, roneli approved these changes
LGTM

2022-01-17 20:07 UTC, merged